/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Component;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import model.Person;

/**
 *
 * @author jtwes
 */
public class CreateJPanelPerson extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person;
    public CreateJPanelPerson(Person p) {
        initComponents();
        //initializing person labelled as p
        person = p;
        
        //Placing my radiobuttons in a group so they cannot both be selected.
        btnGroupMaritalStatus.add(radioMarried);
        btnGroupMaritalStatus.add(radioSingle);
    }
    
    ///Method to validate all JTextFields, returns false if any field is blank.
    public boolean validateAllFieldsNotEmpty(){
        // for loop, grabs all components in "this" class instance
        for (Component c : this.getComponents()){
        // if the component is a jtextfield we check if it is blank, this also reassigns the component to f which is now a jtextfield object.   
            if (c instanceof JTextField f){
                if (f.getText().isBlank()){                                  
                   return false; 
                }
            }
        }
            return true;
    }
    
    
        public void clearAllFields(){
        // for loop, grabs all components in "this" class instance
        for (Component c : this.getComponents()){
        // if the component is a jtextfield set text to "", if its a radio, remove selection   
            if (c instanceof JTextField f){
                    f.setText("");
            }
            }
        //removes radio button selection
         btnGroupMaritalStatus.clearSelection();
        }

    //Method to validate that one of 2 radio buttons is selected.
    public boolean validateRadioButtons(JRadioButton a, JRadioButton b){
        //if one of the two buttons is selected, radio buttons are valid
        if (a.isSelected() || b.isSelected()){
            return true;
        }
            return false;
    }
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupMaritalStatus = new javax.swing.ButtonGroup();
        lblPersonProfile = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        radioMarried = new javax.swing.JRadioButton();
        radioSingle = new javax.swing.JRadioButton();
        lblAge = new javax.swing.JLabel();
        lblMaritalStatus1 = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        fieldOccupation = new javax.swing.JTextField();
        lblOccupation = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 200, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPersonProfile.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblPersonProfile.setText("Person Profile");
        add(lblPersonProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 215, 90));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        radioMarried.setText("Married");
        add(radioMarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        radioSingle.setText("Single");
        add(radioSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        lblAge.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblAge.setText("Age");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        lblMaritalStatus1.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblMaritalStatus1.setText("Mrital Status");
        add(lblMaritalStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        lblLastName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblLastName.setText("Last Name");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        lblFirstName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblFirstName.setText("First Name");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));
        add(fieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 100, -1));
        add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 100, -1));
        add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 100, -1));
        add(fieldOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 100, -1));

        lblOccupation.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblOccupation.setText("Occupation");
        add(lblOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

  
    
  
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       // Save data to our person profile object.
       boolean valid=true;
       String message = "Successfully saved";
       //ensure all fields are filled and radio buttons have a selection.
       if (!validateAllFieldsNotEmpty() && !validateRadioButtons(radioMarried,radioSingle) ){
           valid=false;
           message="Please enter all information before saving.";
           JOptionPane.showMessageDialog(this, message, "Failed to Save",JOptionPane.INFORMATION_MESSAGE);

       }else{
            
            //getting text and validations for first name
            String firstName = fieldFirstName.getText();
            if (firstName.length()>99){
                valid=false;
                message="please enter a first name less than 100 characters";
            }
            if (!firstName.matches("[a-zA-Z ]+")){
                valid=false;
                message="please enter a first name with only letters";
            }
            
            //getting text and validations for last name   
            String lastName = fieldLastName.getText();
            if (lastName.length()>99){
                valid=false;
                message="please enter a last name less than 100 characters";
            }
            if (!lastName.matches("[a-zA-Z ]+")){
                valid=false;
                message="please enter a last name with only letters";
            }
            
            String occupation = fieldOccupation.getText();
            if (occupation.length()>99){
                valid=false;
                message="please enter a last name less than 100 characters";
            }
            if (!occupation.matches("[a-zA-Z ]+")){
                valid=false;
                message="please enter a last name with only letters";
            }
            
            //getting Age and validation
            int age = 0; //needs to start 0 due to the try/catch
            //try converting the age field to an integer, if it fails show an error message
            try{
                age = Integer.parseInt(fieldAge.getText());
                    }catch (NumberFormatException e){
                        valid=false;
                        message="please enter a valid age 0 to 150";
            }
            //validate age
            if(age > 150 || age < 0){
                valid=false;
                message="please enter a valid age from 0 to 150";
            }
            
            ///setting the married status based on if radioMarried is selected or not.
            boolean married;
            if (radioMarried.isSelected()){
                married = true;
            }else{
                married = false;
            }
          

            //////validation check,
           if (!valid){
                JOptionPane.showMessageDialog(this, message, "Failed to Save",JOptionPane.INFORMATION_MESSAGE);
           }else{
                           /// setting all the bank data in our bank product.
            person.setFirstName(firstName);
            person.setLastName(lastName);
            person.setAge(age);
            person.setMarried(married);
            person.setOccupation(occupation);
               
            

               
               
               JOptionPane.showMessageDialog(this, "Saved Successfully", "Saved Successfully",JOptionPane.INFORMATION_MESSAGE);
               clearAllFields();
           }
       }


        

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupMaritalStatus;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldOccupation;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMaritalStatus1;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblPersonProfile;
    private javax.swing.JRadioButton radioMarried;
    private javax.swing.JRadioButton radioSingle;
    // End of variables declaration//GEN-END:variables
}
