/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Component;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import model.Person;

/**
 *
 * @author jtwes
 */
public class CreateJPanelLocalAddress extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person;
    public CreateJPanelLocalAddress(Person p) {
        initComponents();
        //store shared person object
        person = p;

    }
    
    ///Method to validate all JTextFields, returns false if any field is blank.
    public boolean validateAllFieldsNotEmpty(){
        // for loop, grabs all components in "this" class instance
        for (Component c : this.getComponents()){
        // if the component is a jtextfield we check if it is blank, this also reassigns the component to f which is now a jtextfield object.   
            if (c instanceof JTextField f){
                if (f.getText().isBlank()){                                  
                   return false; 
                }
            }
        }
            return true;
    }
    
    public void clearAllFields(){
    // for loop, grabs all components in "this" class instance
    for (Component c : this.getComponents()){
    // if the component is a jtextfield set text to "", if its a radio, remove selection   
        if (c instanceof JTextField f){
                f.setText("");
        }
        }
    //removes radio button selection
     btnGroupMaritalStatus.clearSelection();
    }
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupMaritalStatus = new javax.swing.ButtonGroup();
        lblLocalAddress = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblStreetName = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        fieldCity = new javax.swing.JTextField();
        fieldUnitNumber = new javax.swing.JTextField();
        fieldStreetName = new javax.swing.JTextField();
        fieldZipCode = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        fieldCountry = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        fieldPersonName = new javax.swing.JTextField();
        lblPersonName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 200, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLocalAddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblLocalAddress.setText("Local Address");
        add(lblLocalAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 196, 58));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, -1, -1));

        lblStreetName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblStreetName.setText("Street Name");
        add(lblStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, -1, -1));

        lblUnitNumber.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblUnitNumber.setText("Unit Number");
        add(lblUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        lblCity.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));
        add(fieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 100, -1));
        add(fieldUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 100, -1));
        add(fieldStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 100, -1));
        add(fieldZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 100, -1));

        lblCountry.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblCountry.setText("Country");
        add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));
        add(fieldCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 100, -1));

        lblZipCode.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblZipCode.setText("Zip Code");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));
        add(fieldPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 100, -1));

        lblPersonName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblPersonName.setText("Name");
        add(lblPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

  
    
  
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       // Save data to our person profile object.
       boolean valid=true;
       String message = "Successfully saved";
       //ensure all fields are filled 
       if (!validateAllFieldsNotEmpty() ){
           valid=false;
           message="Please enter all information before saving.";
           JOptionPane.showMessageDialog(this, message, "Failed to Save",JOptionPane.INFORMATION_MESSAGE);

       }else{
                    
            //getting text and validations for street name
            String street = fieldStreetName.getText();
            if (street.length()>99){
                valid=false;
                message="please enter a street name less than 100 characters";
            }
            
            //getting text and validations for person Name  
            String personName = fieldPersonName.getText();
            if (personName.length()>49){
                valid=false;
                message="please enter a persons name with less than 50 characters";
            }else if (!personName.matches("[a-zA-Z]+")){
                valid=false;
                message="please enter a name with only letters";
            }
            
            //getting text and validations for city
            String city = fieldCity.getText();
            if (city.length()>99){
                valid=false;
                message="please enter a city name less than 100 characters";
            }
            if (!city.matches("[a-zA-Z ]+")){
                valid=false;
                message="please enter a city name with only letters";
            }
            
            //getting text and validations for unit
            String unit = fieldUnitNumber.getText();
            if (unit.length()>9){
                valid=false;
                message="please enter a unit with less than 10 characters";
            }

            //getting text and validations for zip code
            String zipCode = fieldZipCode.getText();
            if (zipCode.length()>15){
                valid=false;
                message="please enter a unit with less than 16 characters";
            }else if (!zipCode.matches("[0-9]+")){
                valid=false;
                message="please enter a Zip Code with numbers only";
            }
            
            //getting text and validations for first name
            String country = fieldCountry.getText();
            if (country.length()>100){
                valid=false;
                message="please enter a country with less than 100 characters";
            }else if (!country.matches("[a-zA-Z ]+")){
                valid=false;
                message="please enter a country with only letters";
            }
            
            

            //////validation check,
           if (!valid){
                JOptionPane.showMessageDialog(this, message, "Failed to Save",JOptionPane.INFORMATION_MESSAGE);
           }else{
                           //set all the fields into persons local address object.   
            person.getLocalAddress().setCity(city);  
            person.getLocalAddress().setCountry(country);
            person.getLocalAddress().setStreetName(street);
            person.getLocalAddress().setUnitNum(unit);
            person.getLocalAddress().setZipCode(zipCode);
            person.getLocalAddress().setPersonName(personName);
               
            JOptionPane.showMessageDialog(this, "Saved Successfully", "Saved Successfully",JOptionPane.INFORMATION_MESSAGE);
            clearAllFields();   
           }
       }


        

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupMaritalStatus;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCountry;
    private javax.swing.JTextField fieldPersonName;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldUnitNumber;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblLocalAddress;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JLabel lblZipCode;
    // End of variables declaration//GEN-END:variables
}
