/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Component;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import model.Person;

/**
 *
 * @author jtwes
 */
public class CreateJPanelBankAccount extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person;
    public CreateJPanelBankAccount(Person p) {
        initComponents();
        //initializing person labelled as p
        person = p;
        
        //Placing my radiobuttons in a group so they cannot both be selected.
    }
    
    ///Method to validate all JTextFields, returns false if any field is blank.
    public boolean validateAllFieldsNotEmpty(){
        // for loop, grabs all components in "this" class instance
        for (Component c : this.getComponents()){
        // if the component is a jtextfield we check if it is blank, this also reassigns the component to f which is now a jtextfield object.   
            if (c instanceof JTextField f){
                if (f.getText().isBlank()){                                  
                   return false; 
                }
            }
        }
            return true;
    }
    public void clearAllFields(){
        // for loop, grabs all components in "this" class instance
        for (Component c : this.getComponents()){
        // if the component is a jtextfield set text to "", if its a radio, remove selection   
            if (c instanceof JTextField f){
                    f.setText("");
            }
            }
        //removes radio button selection
         btnGroupMaritalStatus.clearSelection();
        }

    //Method to validate that one of 2 radio buttons is selected.
    public boolean validateRadioButtons(JRadioButton a, JRadioButton b){
        //if one of the two buttons is selected, radio buttons are valid
        if (a.isSelected() || b.isSelected()){
            return true;
        }
            return false;
    }
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupMaritalStatus = new javax.swing.ButtonGroup();
        lblBankInformation1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblBankName = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblGrowth = new javax.swing.JLabel();
        fieldGrowth = new javax.swing.JTextField();
        fieldBalance = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldAccountNumber = new javax.swing.JTextField();
        lblPIN = new javax.swing.JLabel();
        fieldPIN = new javax.swing.JTextField();
        lblAccountNumber = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        fieldPersonName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(220, 200, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBankInformation1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblBankInformation1.setText("Bank Information");
        add(lblBankInformation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 196, 58));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, -1, -1));

        lblBankName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        lblBalance.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblBalance.setText("Balance  $");
        add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        lblGrowth.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblGrowth.setText("Growth %");
        add(lblGrowth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));
        add(fieldGrowth, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 100, -1));
        add(fieldBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 100, -1));
        add(fieldBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 100, -1));
        add(fieldAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 100, -1));

        lblPIN.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblPIN.setText("PIN");
        add(lblPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));
        add(fieldPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 100, -1));

        lblAccountNumber.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblAccountNumber.setText("Account Number");
        add(lblAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        lblPersonName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblPersonName.setText("Name");
        add(lblPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));
        add(fieldPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

  
    
  
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       // Save data to our person profile object.
       boolean valid=true;
       String message = "Successfully saved";
       //ensure all fields are filled and radio buttons have a selection.
       if (!validateAllFieldsNotEmpty() ){
           valid=false;
           message="Please enter all information before saving.";
           JOptionPane.showMessageDialog(this, message, "Failed to Save",JOptionPane.INFORMATION_MESSAGE);

       }else{
            
                      
            //getting text and validations for bank account  
            String bankAccount = fieldAccountNumber.getText();
            if (bankAccount.length()>20){
                valid=false;
                message="please enter an account number with less than 20 characters";
            }else if (!bankAccount.matches("[0-9]+")){
                valid=false;
                message="please enter an account number with only numbers";
            }
            
                        //getting text and validations for person Name  
            String personName = fieldPersonName.getText();
            if (personName.length()>49){
                valid=false;
                message="please enter a persons name with less than 50 characters";
            }else if (!personName.matches("[a-zA-Z]+")){
                valid=false;
                message="please enter a name with only letters";
            }
            
            
            //getting text and validations for bank name  
            String bankName = fieldBankName.getText();
            if (bankName.length()>100){
                valid=false;
                message="please enter a valid Bank name";
            }
            if (!bankName.matches("[a-zA-Z]+")){
                valid=false;
                message="please enter a bank name with only letters";
            }
            
                        //getting Age and validation
            double balance = 0; //needs to start 0 due to the try/catch
            //does not accept values that are larger than 12 digits. protects from overflow
            if (fieldBalance.getText().length()>12){
                valid=false;
                message="please enter a valid balance.";
            }
            try{ //try converting the balance field to a double, if it fails show an error message
                balance = Double.parseDouble(fieldBalance.getText());
                    }catch (NumberFormatException e){
                        valid=false;
                        message="please enter a valid balance using only numbers";
            }

            
                        //getting text and validations for first name
            String pin = fieldPIN.getText();
            if (pin.length()!=4){
                valid=false;
                message="please enter a valid 4 digit pin";
            }
            if (!pin.matches("[0-9]+")){
                valid=false;
                message="please enter a PIN with numbers only";
            }

            float growth = 0.0f; //needs to start 0 due to the try/catch
            //does not accept values that are larger than the 12 digits. protects from overflow
            if (fieldGrowth.getText().length()>12){
                valid=false;
                message="please enter a valid growth percentage.";
            }
            try{ //try converting the growth field to a float, if it fails show an error message
                growth = Float.parseFloat(fieldGrowth.getText());
                    }catch (NumberFormatException e){
                        valid=false;
                        message="please enter a valid growth percentage";
            }
            
            
            //////validation check,
           if (!valid){
                JOptionPane.showMessageDialog(this, message, "Failed to Save",JOptionPane.INFORMATION_MESSAGE);
           }else{
            /// setting all the bank data in our bank product.
            person.getBankAccount().setAccountNumber(bankAccount);
            person.getBankAccount().setBankName(bankName);
            person.getBankAccount().setYearlyGrowth(growth);
            person.getBankAccount().setPin(pin);
            person.getBankAccount().setCurrentBalance(balance);
            person.getBankAccount().setPersonName(personName);
               
           JOptionPane.showMessageDialog(this, "Saved Successfully", "Saved Successfully",JOptionPane.INFORMATION_MESSAGE);
           clearAllFields();
           }
       }


        

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupMaritalStatus;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAccountNumber;
    private javax.swing.JTextField fieldBalance;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldGrowth;
    private javax.swing.JTextField fieldPIN;
    private javax.swing.JTextField fieldPersonName;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankInformation1;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblGrowth;
    private javax.swing.JLabel lblPIN;
    private javax.swing.JLabel lblPersonName;
    // End of variables declaration//GEN-END:variables
}
