/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Component;
import java.awt.Container;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import model.Person;

/**
 *
 * @author jtwes
 */
public class CreateJPanelHomeAddress extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person;
    public CreateJPanelHomeAddress(Person p) {
        initComponents();
        //initializing person labelled as p
        person = p;
  
    }
    
    ///Method to validate all JTextFields, returns false if any field is blank.
    public boolean validateAllFieldsNotEmpty(){
        // for loop, grabs all components in "this" class instance
        for (Component c : this.getComponents()){
        // if the component is a jtextfield we check if it is blank, this also reassigns the component to f which is now a jtextfield object.   
            if (c instanceof JTextField f){
                if (f.getText().isBlank()){                                  
                   return false; 
                }
            }
        }
            return true;
    }
    

    //Method to validate that one of 2 radio buttons is selected.
    public boolean validateRadioButtons(JRadioButton a, JRadioButton b){
        //if one of the two buttons is selected, radio buttons are valid
        if (a.isSelected() || b.isSelected()){
            return true;
        }
            return false;
    }
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupMaritalStatus = new javax.swing.ButtonGroup();
        lblHomeAddress = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblStreetName = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        fieldCity = new javax.swing.JTextField();
        fieldUnitNumber = new javax.swing.JTextField();
        fieldStreetName = new javax.swing.JTextField();
        fieldZipCode = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        fieldCountry = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 200, 200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomeAddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblHomeAddress.setText("Home Address");
        add(lblHomeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 196, 58));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, -1, -1));

        lblStreetName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblStreetName.setText("Street Name");
        add(lblStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        lblUnitNumber.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblUnitNumber.setText("Unit Number");
        add(lblUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        lblCity.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));
        add(fieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 100, -1));
        add(fieldUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, -1));
        add(fieldStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 100, -1));
        add(fieldZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 100, -1));

        lblCountry.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblCountry.setText("Country");
        add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));
        add(fieldCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 100, -1));

        lblZipCode.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblZipCode.setText("Zip Code");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

  
    
  
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       // Save data to our person profile object.
       boolean valid=true;
       String message = "Successfully saved";
       //ensure all fields are filled and radio buttons have a selection.
       if (!validateAllFieldsNotEmpty() ){
           valid=false;
           message="Please enter all information before saving.";
           JOptionPane.showMessageDialog(this, message, "Failed to Save",JOptionPane.INFORMATION_MESSAGE);

       }else{
            
                       
            //getting text and validations for first name
            String street = fieldStreetName.getText();
            if (street.length()>99){
                valid=false;
                message="please enter a street name less than 100 characters";
            }
            
                        //getting text and validations for first name
            String city = fieldCity.getText();
            if (city.length()>99){
                valid=false;
                message="please enter a city name less than 100 characters";
            }
            if (!city.matches("[a-zA-Z ]+")){
                valid=false;
                message="please enter a city name with only letters";
            }
            
            //getting text and validations for first name
            String unit = fieldUnitNumber.getText();
            if (unit.length()>9){
                valid=false;
                message="please enter a unit with less than 10 characters";
            }

            
            //getting text and validations for first name
            String country = fieldCountry.getText();
            if (country.length()>100){
                valid=false;
                message="please enter a country with less than 100 characters";
            }
            if (!country.matches("[a-zA-Z ]+")){
                valid=false;
                message="please enter a country with only letters";
            }

            //////validation check,
           if (!valid){
                JOptionPane.showMessageDialog(this, message, "Failed to Save",JOptionPane.INFORMATION_MESSAGE);
           }else{
               
               
               JOptionPane.showMessageDialog(this, "Saved Successfully", "Saved Successfully",JOptionPane.INFORMATION_MESSAGE);
           }
       }


        

    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupMaritalStatus;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCountry;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldUnitNumber;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JLabel lblZipCode;
    // End of variables declaration//GEN-END:variables
}
