/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Person;

/**
 *
 * @author jtwes
 */
public class ViewJPanelLocalAddress extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    public ViewJPanelLocalAddress(Person p) {
        initComponents();
        person = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLocalAddress = new javax.swing.JLabel();
        lblStreetName = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        fieldCity = new javax.swing.JTextField();
        fieldUnitNumber = new javax.swing.JTextField();
        fieldStreetName = new javax.swing.JTextField();
        fieldZipCode = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        fieldCountry = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 252, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLocalAddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblLocalAddress.setText("Local Address");
        add(lblLocalAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 196, 58));

        lblStreetName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblStreetName.setText("Street Name");
        add(lblStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        lblUnitNumber.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblUnitNumber.setText("Unit Number");
        add(lblUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        lblCity.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));
        add(fieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, -1));
        add(fieldUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 100, -1));
        add(fieldStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 100, -1));
        add(fieldZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 100, -1));

        lblCountry.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblCountry.setText("Country");
        add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));
        add(fieldCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 100, -1));

        lblZipCode.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblZipCode.setText("Zip Code");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCountry;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldUnitNumber;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblLocalAddress;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JLabel lblZipCode;
    // End of variables declaration//GEN-END:variables
}
