/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Person;

/**
 *
 * @author jtwes
 */
public class ViewJPanelBankAccount extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    public ViewJPanelBankAccount(Person p) {
        initComponents();
        person = p;
        displayInformation();
        
    }
    
    
    private void displayInformation(){
            fieldBankName.setText(person.getBankAccount().getBankName());
            fieldPersonName.setText(person.getBankAccount().getPersonName());
            fieldAccountNumber.setText(person.getBankAccount().getAccountNumber());
            fieldPIN.setText(person.getBankAccount().getPin());
            
            //convert double back to string for display
            String cb = String.valueOf(person.getBankAccount().getCurrentBalance());
            fieldBalance.setText(cb);
            
            //convert double back to string for display
            String yg = String.valueOf(person.getBankAccount().getYearlyGrowth());
            fieldGrowth.setText(yg);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBankInformation1 = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblGrowth = new javax.swing.JLabel();
        fieldGrowth = new javax.swing.JTextField();
        fieldBalance = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldAccountNumber = new javax.swing.JTextField();
        lblPIN = new javax.swing.JLabel();
        fieldPIN = new javax.swing.JTextField();
        lblAccountNumber = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        fieldPersonName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(252, 252, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBankInformation1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblBankInformation1.setText("Bank Information");
        add(lblBankInformation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 196, 58));

        lblBankName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        lblBalance.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblBalance.setText("Balance");
        add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        lblGrowth.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblGrowth.setText("Growth %");
        add(lblGrowth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));
        add(fieldGrowth, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 100, -1));
        add(fieldBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 100, -1));
        add(fieldBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 100, -1));
        add(fieldAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 100, -1));

        lblPIN.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblPIN.setText("PIN");
        add(lblPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));
        add(fieldPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 100, -1));

        lblAccountNumber.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblAccountNumber.setText("Account Number");
        add(lblAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        lblPersonName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblPersonName.setText("Name");
        add(lblPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));
        add(fieldPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 100, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAccountNumber;
    private javax.swing.JTextField fieldBalance;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldGrowth;
    private javax.swing.JTextField fieldPIN;
    private javax.swing.JTextField fieldPersonName;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankInformation1;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblGrowth;
    private javax.swing.JLabel lblPIN;
    private javax.swing.JLabel lblPersonName;
    // End of variables declaration//GEN-END:variables
}
