/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.Person;

/**
 *
 * @author jtwes
 */
public class ViewJPanelPerson extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    Person person;
    public ViewJPanelPerson(Person p) {
        initComponents();
        person = p;
        displayInformation();
    }

    
        private void displayInformation(){
            fieldBankName.setText(person.getBankAccount().getBankName());
            fieldAccountNumber.setText(person.getBankAccount().getAccountNumber());
            fieldPIN.setText(person.getBankAccount().getPin());
            
            //convert double back to string for display
            String cb = String.valueOf(person.getBankAccount().getCurrentBalance());
            fieldBalance.setText(cb);
            
            //convert double back to string for display
            String yg = String.valueOf(person.getBankAccount().getYearlyGrowth());
            fieldGrowth.setText(yg);
            
            fieldCity.setText(person.getHomeAddress().getCity());
            fieldCountry.setText(person.getHomeAddress().getCountry());
            fieldStreetName.setText(person.getHomeAddress().getStreetName());
            fieldUnitNumber.setText(person.getHomeAddress().getUnitNum());
            fieldZipCode.setText(person.getHomeAddress().getZipCode());
            fieldFirstName.setText(person.getFirstName());
            fieldLastName.setText(person.getLastName());
            
            //convert int back into string
            fieldAge.setText(String.valueOf(person.getAge()));
            
            fieldOccupation.setText(person.getOccupation());
            
            if (person.isMarried()){
                radioMarried.setSelected(true);
                radioSingle.setSelected(false);
            }else{
                radioMarried.setSelected(false);
                radioSingle.setSelected(true);
            }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHomeAddress = new javax.swing.JLabel();
        lblPersonProfile = new javax.swing.JLabel();
        lblBankInformation1 = new javax.swing.JLabel();
        radioMarried = new javax.swing.JRadioButton();
        radioSingle = new javax.swing.JRadioButton();
        lblAge = new javax.swing.JLabel();
        lblMaritalStatus1 = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        lblBankName = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblGrowth = new javax.swing.JLabel();
        fieldGrowth = new javax.swing.JTextField();
        fieldBalance = new javax.swing.JTextField();
        fieldBankName = new javax.swing.JTextField();
        fieldAccountNumber = new javax.swing.JTextField();
        lblPIN = new javax.swing.JLabel();
        fieldPIN = new javax.swing.JTextField();
        lblAccountNumber = new javax.swing.JLabel();
        lblStreetName = new javax.swing.JLabel();
        lblUnitNumber = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        fieldCity = new javax.swing.JTextField();
        fieldUnitNumber = new javax.swing.JTextField();
        fieldStreetName = new javax.swing.JTextField();
        fieldZipCode = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        fieldCountry = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        fieldOccupation = new javax.swing.JTextField();
        lblOccupation = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 252, 242));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomeAddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblHomeAddress.setText("Home Address");
        add(lblHomeAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 325, 196, 58));

        lblPersonProfile.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblPersonProfile.setText("Person Profile");
        add(lblPersonProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 51, 215, 90));

        lblBankInformation1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblBankInformation1.setText("Bank Information");
        add(lblBankInformation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 196, 58));

        radioMarried.setText("Married");
        add(radioMarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        radioSingle.setText("Single");
        add(radioSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        lblAge.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblAge.setText("Age");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 228, -1, -1));

        lblMaritalStatus1.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblMaritalStatus1.setText("Mrital Status");
        add(lblMaritalStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        lblLastName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblLastName.setText("Last Name");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 193, -1, -1));

        lblFirstName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblFirstName.setText("First Name");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 152, -1, -1));
        add(fieldAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 223, 100, -1));
        add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 188, 100, -1));
        add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 147, 100, -1));

        lblBankName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblBankName.setText("Bank Name");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        lblBalance.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblBalance.setText("Balance");
        add(lblBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        lblGrowth.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblGrowth.setText("Growth %");
        add(lblGrowth, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));
        add(fieldGrowth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 100, -1));
        add(fieldBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 100, -1));
        add(fieldBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 100, -1));
        add(fieldAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 100, -1));

        lblPIN.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblPIN.setText("PIN");
        add(lblPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));
        add(fieldPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 100, -1));

        lblAccountNumber.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblAccountNumber.setText("Account Number");
        add(lblAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, -1, -1));

        lblStreetName.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblStreetName.setText("Street Name");
        add(lblStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        lblUnitNumber.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblUnitNumber.setText("Unit Number");
        add(lblUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        lblCity.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblCity.setText("City");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));
        add(fieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 100, -1));
        add(fieldUnitNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 100, -1));
        add(fieldStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 100, -1));
        add(fieldZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 100, -1));

        lblCountry.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblCountry.setText("Country");
        add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, -1, -1));
        add(fieldCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 100, -1));

        lblZipCode.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblZipCode.setText("Zip Code");
        add(lblZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));
        add(fieldOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 100, -1));

        lblOccupation.setFont(new java.awt.Font("Minion Pro", 0, 14)); // NOI18N
        lblOccupation.setText("Occupation");
        add(lblOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAccountNumber;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldBalance;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldCountry;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldGrowth;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldOccupation;
    private javax.swing.JTextField fieldPIN;
    private javax.swing.JTextField fieldStreetName;
    private javax.swing.JTextField fieldUnitNumber;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBankInformation1;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGrowth;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMaritalStatus1;
    private javax.swing.JLabel lblOccupation;
    private javax.swing.JLabel lblPIN;
    private javax.swing.JLabel lblPersonProfile;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblUnitNumber;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JRadioButton radioMarried;
    private javax.swing.JRadioButton radioSingle;
    // End of variables declaration//GEN-END:variables
}
