/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleManager;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Service;
import model.ServiceDirectory;
import model.ServiceType;
import model.Vehicle;

/**
 *
 * @author jtwes
 */
public class CreateServiceJPanel extends javax.swing.JPanel {
    //declare vars
    JPanel userProcessContainer;
    ServiceDirectory serviceDirectory;

    /**
     * Creates new form CreateServiceJPanel
     */
    
    private Vehicle vehicle;
    
    public CreateServiceJPanel(JPanel container, ServiceDirectory directory, ServiceType serviceTypes) {
        initComponents();
        //assign vars with passed through parameters
        userProcessContainer = container;
        serviceDirectory= directory;
        this.vehicle = vehicle;

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblServiceType = new javax.swing.JLabel();
        lblCost = new javax.swing.JLabel();
        lblMachanicFirstName = new javax.swing.JLabel();
        txtMechanicFirstName = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        lblMechanicLastName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtMechanicLastName = new javax.swing.JTextField();
        lblServiceDuration = new javax.swing.JLabel();
        txtServiceDuration = new javax.swing.JTextField();
        txtServiceType = new javax.swing.JTextField();

        setBackground(new java.awt.Color(232, 242, 242));

        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setText("Create Service");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblServiceType.setText("Service Type");

        lblCost.setText("Cost");

        lblMachanicFirstName.setText("Mechanic First Name");

        lblMechanicLastName.setText("Mechanic Last Name");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Register Service");

        lblServiceDuration.setText("Service Duration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblServiceType)
                                .addComponent(lblCost)
                                .addComponent(lblMachanicFirstName))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblMechanicLastName)
                                .addComponent(lblServiceDuration)))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMechanicLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMechanicFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtServiceType, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCost, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtServiceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServiceType)
                    .addComponent(txtServiceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCost)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMechanicFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMachanicFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMechanicLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMechanicLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtServiceDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceDuration))
                .addGap(52, 52, 52)
                .addComponent(btnCreate)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents
        //back button with table refresh
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ManageServicesJPanel manageServicesJPanel = (ManageServicesJPanel) lastPanel;
        manageServicesJPanel.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

       //create new service
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        float cost;
        int duration;
        
       
       String mechanicFirstName = txtMechanicFirstName.getText();
       String mechanicLastName = txtMechanicLastName.getText();
       String serviceType = txtServiceType.getText();
       
       if (mechanicFirstName.isBlank() || mechanicLastName.isBlank()|| txtCost.getText().isBlank()|| txtServiceDuration.getText().isBlank())
       {
           JOptionPane.showMessageDialog(this,"All fields are mandatory.","ERROR", JOptionPane.ERROR_MESSAGE);
           return;
       }
       
    
       
           //error handling on bad input
        try {
          cost = Float.parseFloat(txtCost.getText());
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this,"Please use only decimal numbers for the cost.","Warning",JOptionPane.WARNING_MESSAGE);
         return;
        }
        //error handling on bad input
        try {
         duration = Integer.parseInt(txtServiceDuration.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Please use only a whole number for the cost.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
        }
        //validation tree, check for length of input, and match characters to what we expect. return out of method if anything does not meet standard
        if (mechanicFirstName.length() > 50 || !mechanicFirstName.matches("[a-zA-Z _-]+")) {
            JOptionPane.showMessageDialog(this,"Mechanic first name must be 50 characters or less and may only contain letters, spaces, underscores, and hyphens.","Invalid First Name",JOptionPane.ERROR_MESSAGE);
            return;
        }else if (mechanicLastName.length() > 50 || !mechanicLastName.matches("[a-zA-Z _-]+")) {
            JOptionPane.showMessageDialog(this,"Mechanic last name must be 50 characters or less and may only contain letters, spaces, underscores, and hyphens.","Invalid First Name",JOptionPane.ERROR_MESSAGE);
            return;
        } else if (serviceType.length() > 50 || !serviceType.matches("[a-zA-Z _-]+")) {
            JOptionPane.showMessageDialog(this,"Service must be 50 characters or less and may only contain letters, spaces, underscores, and hyphens.","Invalid First Name",JOptionPane.ERROR_MESSAGE);
            return;
        }else if (cost < 0 || cost > 10000000) {
            JOptionPane.showMessageDialog(this,"Cost must be between 0 and 10,000,000.","Invalid Cost",JOptionPane.ERROR_MESSAGE);
            return;
        } else if (duration < 0 || duration > 10000000) {
            JOptionPane.showMessageDialog(this,"Service duration must be between 0 and 10,000,000 minutes.","Invalid Duration",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //find the last item in the service directory
        Service lastService = serviceDirectory.getServices().isEmpty() ? null : serviceDirectory.getServices().get(serviceDirectory.getServices().size() - 1);
        
        //create new service obj.
        Service a = serviceDirectory.addService();
        
        //if there is a no item in the service directory, set to 1, otherwise add 1 from the last ID
        a.setServiceID(lastService == null ? 1 : lastService.getServiceID() + 1);
        
       
        //populate object a with data
        a.setCost(cost);
        a.setMechanicFirstName(mechanicFirstName);
        a.setMechanicLastName(mechanicLastName);
        a.setServiceDuration(duration);
        a.setServiceType(serviceType);
       
        JOptionPane.showMessageDialog(this,"Service successfully created","Information", JOptionPane.INFORMATION_MESSAGE);
        
        //clear text fields
        txtCost.setText("");
        txtMechanicFirstName.setText("");
        txtMechanicLastName.setText("");
        txtServiceDuration.setText("");
        txtServiceType.setText("");

    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblMachanicFirstName;
    private javax.swing.JLabel lblMechanicLastName;
    private javax.swing.JLabel lblServiceDuration;
    private javax.swing.JLabel lblServiceType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtMechanicFirstName;
    private javax.swing.JTextField txtMechanicLastName;
    private javax.swing.JTextField txtServiceDuration;
    private javax.swing.JTextField txtServiceType;
    // End of variables declaration//GEN-END:variables
}
