/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleManager;

import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Owner;
import model.OwnersDirectory;
import model.Service;
import model.ServiceDirectory;
import model.ServiceType;
import model.Vehicle;
import model.VehicleDirectory;

/**
 *
 * @author jtwes
 */
public class CreateVehicleJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    VehicleDirectory vehicleDirectory;
    ServiceDirectory serviceDirectory;
    ServiceType serviceTypes;
    OwnersDirectory ownersDirectory;
    /**
     * Creates new form CreateVehicleJPanel
     */
    public CreateVehicleJPanel(JPanel container, VehicleDirectory vehicleDirectory, ServiceDirectory serviceDirectory, ServiceType serviceType, OwnersDirectory ownersDirectory) {
        initComponents();
        
        userProcessContainer = container;
        this.serviceDirectory = serviceDirectory;
        this.vehicleDirectory = vehicleDirectory;
        this.ownersDirectory = ownersDirectory;
        this.serviceTypes = serviceTypes;

        comboServiceOpted.removeAllItems();

        for (String type : serviceType.getServiceTypes()) {
            comboServiceOpted.addItem(type);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        lblRegistrationNumber = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txtRegistrationNumber = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        comboServiceOpted = new javax.swing.JComboBox<>();
        lblServiceOpted = new javax.swing.JLabel();

        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setText("Register Service");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblRegistrationNumber.setText("Registration Number");

        lblYear.setText("Year");

        lblLastName.setText("Last Name");

        lblMake.setText("Make");

        lblModel.setText("Model");

        lblFirstName.setText("First Name");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Register Vehicle");

        comboServiceOpted.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblServiceOpted.setText("Service Opted");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(comboServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMake)
                                            .addComponent(lblModel)
                                            .addComponent(lblYear)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblRegistrationNumber)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMake, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtModel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRegistrationNumber)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLastName)
                                    .addComponent(lblFirstName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(225, 225, 225))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblServiceOpted)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addGap(7, 7, 7)
                .addComponent(lblTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMake)
                            .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModel)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegistrationNumber)
                            .addComponent(txtRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboServiceOpted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServiceOpted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] panelStack = userProcessContainer.getComponents();
        JPanel lastPanel = (JPanel) panelStack[panelStack.length - 1];
        ManageVehiclesJPanel manageVehiclesJPanel = (ManageVehiclesJPanel) lastPanel;
        manageVehiclesJPanel.populateTable();
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

    int vehicleID;
    int year;

    String make = txtMake.getText();
    String model = txtModel.getText();
    String registrationNumber = txtRegistrationNumber.getText();
    Object serviceOpted = comboServiceOpted.getSelectedItem();

    String ownerFirstName = txtFirstName.getText();
    String ownerLastName = txtLastName.getText();
    
    
    if (make.isBlank() || model.isBlank() || registrationNumber.isBlank() || ownerFirstName.isBlank() || ownerLastName.isBlank()) { 
        JOptionPane.showMessageDialog(this, "All fields are mandatory.", "ERROR", JOptionPane.ERROR_MESSAGE); 
        return; 
    }
    
    try {
        year = Integer.parseInt(txtYear.getText());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,"Vehicle year must be a whole number.","Warning",JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (year < 0 || year > 10000000) {
        JOptionPane.showMessageDialog(this,"Please enter a valid vehicle year.","Invalid Year",JOptionPane.ERROR_MESSAGE);
        return;
    } else if (make.length() > 50 || !make.matches("[a-zA-Z _-]+")) {
        JOptionPane.showMessageDialog(this,"Make must be 50 characters or less and may only contain letters, spaces, underscores, and hyphens.","Invalid",JOptionPane.ERROR_MESSAGE);
        return;
    } else if (model.length() > 50 || !model.matches("[a-zA-Z _-]+")) {
        JOptionPane.showMessageDialog(this,"Model must be 50 characters or less and may only contain letters, spaces, underscores, and hyphens.","Invalid",JOptionPane.ERROR_MESSAGE);
        return;
    }else if (registrationNumber.length() > 50 || !registrationNumber.matches("[a-zA-Z0-9 _-]+")) {
        JOptionPane.showMessageDialog(this,"Registration Number must be 50 characters or less and may only contain letters, numbers, spaces, underscores, and hyphens.","Invalid",JOptionPane.ERROR_MESSAGE);
        return;   
    }else if (ownerLastName.length() > 50 || !ownerLastName.matches("[a-zA-Z _-]+")) {
        JOptionPane.showMessageDialog(this,"Last Name must be 50 characters or less and may only contain letters, spaces, underscores, and hyphens.","Invalid",JOptionPane.ERROR_MESSAGE);
        return;  
    }else if (ownerFirstName.length() > 50 || !ownerFirstName.matches("[a-zA-Z _-]+")) {
        JOptionPane.showMessageDialog(this,"First Name must be 50 characters or less and may only contain letters, spaces, underscores, and hyphens.","Invalid",JOptionPane.ERROR_MESSAGE);
        return;
    } 
    
    
    Vehicle lastVehicle = vehicleDirectory.getVehicles().isEmpty() ? null : vehicleDirectory.getVehicles().get(vehicleDirectory.getVehicles().size() - 1);
    Owner lastOwner = ownersDirectory.getOwners().isEmpty() ? null : ownersDirectory.getOwners().get(ownersDirectory.getOwners().size() - 1); 
    Owner owner = ownersDirectory.addOwners();
    
    owner.setOwnerID(lastOwner == null ? 1 : lastOwner.getOwnerID() + 1);

    owner.setOwnerFirstName(ownerFirstName);
    owner.setOwnerLastName(ownerLastName);
    owner.setServiceDate(LocalDateTime.now());

    Vehicle vehicle = vehicleDirectory.addVehicle();
    vehicle.setVehicleID(lastVehicle == null ? 1 : lastVehicle.getVehicleID() + 1);

    vehicle.setMake(make);
    vehicle.setModel(model);
    vehicle.setRegistrationNumber(registrationNumber);
    vehicle.setYear(year);
    vehicle.setOwner(owner);
    vehicle.setServiceOpted((Service) serviceOpted);
    
    JOptionPane.showMessageDialog(this,"Vehicle successfully created","Information",JOptionPane.INFORMATION_MESSAGE);
               
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox<String> comboServiceOpted;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblRegistrationNumber;
    private javax.swing.JLabel lblServiceOpted;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtRegistrationNumber;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
