/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.VehicleManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Service;
import model.ServiceDirectory;
import model.ServiceType;

/**
 *
 * @author jtwes
 */
public class ManageServicesJPanel extends javax.swing.JPanel {
    JPanel ContentPanel;
    ServiceDirectory serviceDirectory;
    ServiceType serviceTypes;
    /**
     * Creates new form ManageServicesJPanel
     */
    public ManageServicesJPanel(JPanel container, ServiceDirectory directory, ServiceType serviceTypes) {
        initComponents();
        this.serviceTypes = serviceTypes;
        ContentPanel = container;
        serviceDirectory= directory;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearchBox = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnCreateNewService = new javax.swing.JButton();

        btnBack.setText("<-Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Service");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblTitle.setText("Manage Services");

        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Service ID", "Service Type", "Duration", "Mechanic", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblServices);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnCreateNewService.setText("Create New Service");
        btnCreateNewService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(lblTitle)
                        .addGap(45, 45, 45)
                        .addComponent(btnCreateNewService))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete)
                            .addComponent(btnViewDetails))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewService)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ContentPanel.remove(this);
        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.previous(ContentPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        int selectedRow = tblServices.getSelectedRow();
        
        if (selectedRow >=0){
            Service selectedService = (Service) tblServices.getValueAt(selectedRow,0);
            
            ViewServiceJPanel panel = new ViewServiceJPanel(ContentPanel, serviceDirectory, selectedService, serviceTypes);
            ContentPanel.add("ViewServiceJPanel", panel);
            CardLayout layout = (CardLayout) ContentPanel.getLayout();
            layout.next(ContentPanel);
            
        }else{
            JOptionPane.showConfirmDialog(null, "Please select an service from the list.","Warning",JOptionPane.WARNING_MESSAGE);

        }
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblServices.getSelectedRow();
        
        if (selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected service?","Warning",JOptionPane.WARNING_MESSAGE);
            if(dialogResult == JOptionPane.YES_OPTION){
                Service selectedService = (Service) tblServices.getValueAt(selectedRow,0);
                serviceDirectory.deleteService(selectedService);
                populateTable();
            }
        }else{
            JOptionPane.showConfirmDialog(null, "Please select an service from the list.","Warning",JOptionPane.WARNING_MESSAGE);

        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       
    String searchText = txtSearchBox.getText().trim();

    if (searchText.isBlank()) {
        JOptionPane.showMessageDialog(this, "Please type a Service ID or Service Type to search.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblServices.getModel();
    model.setRowCount(0);

    boolean foundItems = false;

    for (Service a : serviceDirectory.getServices()) {
        if (String.valueOf(a.getServiceID()).equalsIgnoreCase(searchText) || a.getServiceType().toString().equalsIgnoreCase(searchText)) {
            Object[] row = new Object[5];
            row[0] = a;
            row[1] = a.getServiceType();
            row[2] = a.getServiceDuration();
            row[3] = a.getMechanicFirstName() + " " + a.getMechanicLastName();
            row[4] = a.getCost();
            model.addRow(row);
            foundItems = true;
        }
    }

    if (foundItems==false) {
        JOptionPane.showMessageDialog(this, "No services found matching your search.", "Warning", JOptionPane.WARNING_MESSAGE);
        populateTable();
    }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCreateNewServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewServiceActionPerformed
        CreateServiceJPanel panel = new CreateServiceJPanel(ContentPanel, serviceDirectory, serviceTypes);
        ContentPanel.add("CreateServiceJPanel",panel);

        CardLayout layout = (CardLayout) ContentPanel.getLayout();
        layout.next(ContentPanel);     // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateNewServiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateNewService;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblServices;
    private javax.swing.JTextField txtSearchBox;
    // End of variables declaration//GEN-END:variables
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblServices.getModel();
        model.setRowCount(0);
        
        for (Service a:serviceDirectory.getServices()){
            Object[] row = new Object[7];
            row[0] = a;
            row[1] = a.getServiceType();
            row[2] = a.getServiceDuration();
            row[3] = a.getMechanicFirstName()+" "+a.getMechanicLastName();
            row[4] = a.getCost();
            model.addRow(row);
        }
    }

}
