/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.time.LocalDateTime;
import model.Owner;
import model.OwnersDirectory;
import model.Service;
import model.ServiceDirectory;
import model.ServiceType;
import model.Vehicle;
import model.VehicleDirectory;
import ui.VehicleManager.CreateVehicleJPanel;
import ui.VehicleManager.ManageServicesJPanel;
import ui.VehicleManager.ManageVehiclesJPanel;

/**
 *
 * @author jtwes
 */
public class MainJFrame extends javax.swing.JFrame {
    private ServiceDirectory serviceDirectory;
    private VehicleDirectory vehicleDirectory;
    private OwnersDirectory ownersDirectory;
    public ServiceType serviceTypes;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        contentPanel.setLayout(new CardLayout());
        this.serviceDirectory = new ServiceDirectory();
        this.vehicleDirectory = new VehicleDirectory();
        this.serviceTypes = new ServiceType();
        this.ownersDirectory = new OwnersDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        navPanel = new javax.swing.JPanel();
        btnServices = new javax.swing.JButton();
        btnVehicalAndOwner = new javax.swing.JButton();
        btnManageVehicles = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navPanel.setBackground(new java.awt.Color(242, 222, 242));

        btnServices.setText("Manage Services");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnVehicalAndOwner.setText("Register Vehicle & Owner for Service");
        btnVehicalAndOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicalAndOwnerActionPerformed(evt);
            }
        });

        btnManageVehicles.setText("Manage Vehicles");
        btnManageVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehiclesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnServices)
                .addGap(75, 75, 75)
                .addComponent(btnVehicalAndOwner)
                .addGap(63, 63, 63)
                .addComponent(btnManageVehicles)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServices)
                    .addComponent(btnVehicalAndOwner)
                    .addComponent(btnManageVehicles))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(navPanel);

        contentPanel.setBackground(new java.awt.Color(222, 242, 242));
        contentPanel.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Welcome to Vehicle Service Management Application");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        ManageServicesJPanel panel = new ManageServicesJPanel(contentPanel, serviceDirectory, serviceTypes);
        contentPanel.add("ManageServicesJPanel",panel);
        
        CardLayout layout = (CardLayout) contentPanel.getLayout();
        layout.next(contentPanel);        
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnManageVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehiclesActionPerformed
        ManageVehiclesJPanel panel = new ManageVehiclesJPanel(contentPanel, vehicleDirectory, serviceDirectory);
        contentPanel.add("ManageVehiclesJPanel",panel);
        
        CardLayout layout = (CardLayout) contentPanel.getLayout();
        layout.next(contentPanel);  
    }//GEN-LAST:event_btnManageVehiclesActionPerformed

    private void btnVehicalAndOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicalAndOwnerActionPerformed
        CreateVehicleJPanel panel = new CreateVehicleJPanel(contentPanel, vehicleDirectory, serviceDirectory, serviceTypes, ownersDirectory);
        contentPanel.add("CreateVehicleJPanel",panel);
        
        CardLayout layout = (CardLayout) contentPanel.getLayout();
        layout.next(contentPanel);
    }//GEN-LAST:event_btnVehicalAndOwnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageVehicles;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnVehicalAndOwner;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel navPanel;
    // End of variables declaration//GEN-END:variables


    private void generateDemoData(){
        
        Owner newOwner = ownersDirectory.addOwners();
        newOwner.setOwnerFirstName("John");
        newOwner.setOwnerLastName("Doe");
        newOwner.setOwnerID(1);
        newOwner.setServiceDate(LocalDateTime.of(2026, 1, 1, 0, 0));
        
        Vehicle newVehicle = vehicleDirectory.addVehicle();
        newVehicle.setMake("Kia");
        newVehicle.setModel("Soul SE");
        newVehicle.setYear(2014);
        newVehicle.setVehicleID(1);
        newVehicle.setRegistrationNumber("65465564");
        newVehicle.setOwner(newOwner);
        
        Service newService = serviceDirectory.addService();
        newService.setCost(55.5f);
        newService.setMechanicFirstName("Bob");
        newService.setMechanicLastName("Fixit");
        newService.setServiceDuration(95);
        newService.setServiceID(1);
        newService.setServiceType(serviceTypes.getServiceTypes().get(1));
        newVehicle.setServiceOpted(newService);

        
        Owner newOwner2 = ownersDirectory.addOwners();
        newOwner2.setOwnerFirstName("John");
        newOwner2.setOwnerLastName("Doe");
        newOwner2.setOwnerID(2);
        newOwner2.setServiceDate(LocalDateTime.of(2026, 1, 1, 0, 0));
        
        Vehicle newVehicle2 = vehicleDirectory.addVehicle();
        newVehicle2.setMake("Ford");
        newVehicle2.setModel("Taurus xl");
        newVehicle2.setYear(2010);
        newVehicle2.setVehicleID(2);
        newVehicle2.setRegistrationNumber("26234126123");
        newVehicle2.setOwner(newOwner2);
        
        Service newService2 = serviceDirectory.addService();
        newService2.setCost(55.5f);
        newService2.setMechanicFirstName("Bill");
        newService2.setMechanicLastName("Fixit Jr");
        newService2.setServiceDuration(55);
        newService2.setServiceID(2);
        newService2.setServiceType(serviceTypes.getServiceTypes().get(1));
        newVehicle2.setServiceOpted(newService2);

        System.out.print(serviceDirectory.getServices());

    }


}
