/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.time.LocalDateTime;
import model.Owner;
import model.OwnersDirectory;
import model.Service;
import model.ServiceDirectory;
import model.ServiceType;
import model.Vehicle;
import model.VehicleDirectory;
import ui.VehicleManager.CreateVehicleJPanel;
import ui.VehicleManager.ManageServicesJPanel;
import ui.VehicleManager.ManageVehiclesJPanel;

/**
 *
 * @author jtwes
 */
public class MainJFrame extends javax.swing.JFrame {
    private ServiceDirectory serviceDirectory;
    private VehicleDirectory vehicleDirectory;
    private OwnersDirectory ownersDirectory;
    public ServiceType serviceTypes;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        //initialize all the objects on start of application
        contentPanel.setLayout(new CardLayout());
        this.serviceDirectory = new ServiceDirectory();
        this.vehicleDirectory = new VehicleDirectory();
        this.serviceTypes = new ServiceType();
        this.ownersDirectory = new OwnersDirectory();
        //insert demo objects to directories
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        navPanel = new javax.swing.JPanel();
        btnServices = new javax.swing.JButton();
        btnVehicalAndOwner = new javax.swing.JButton();
        btnManageVehicles = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navPanel.setBackground(new java.awt.Color(242, 222, 242));

        btnServices.setText("Manage Services");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnVehicalAndOwner.setText("Register Vehicle & Owner for Service");
        btnVehicalAndOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicalAndOwnerActionPerformed(evt);
            }
        });

        btnManageVehicles.setText("Manage Vehicles");
        btnManageVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehiclesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnServices)
                .addGap(75, 75, 75)
                .addComponent(btnVehicalAndOwner)
                .addGap(63, 63, 63)
                .addComponent(btnManageVehicles)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServices)
                    .addComponent(btnVehicalAndOwner)
                    .addComponent(btnManageVehicles))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(navPanel);

        contentPanel.setBackground(new java.awt.Color(222, 242, 242));
        contentPanel.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME TO THE SERVICE MANAGMENT SYSTEM");
        jLabel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        ManageServicesJPanel panel = new ManageServicesJPanel(contentPanel, serviceDirectory, serviceTypes);
        contentPanel.add("ManageServicesJPanel",panel);
        
        CardLayout layout = (CardLayout) contentPanel.getLayout();
        layout.next(contentPanel);        
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnManageVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehiclesActionPerformed
        ManageVehiclesJPanel panel = new ManageVehiclesJPanel(contentPanel, vehicleDirectory, serviceDirectory);
        contentPanel.add("ManageVehiclesJPanel",panel);
        
        CardLayout layout = (CardLayout) contentPanel.getLayout();
        layout.next(contentPanel);  
    }//GEN-LAST:event_btnManageVehiclesActionPerformed

    private void btnVehicalAndOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicalAndOwnerActionPerformed
        CreateVehicleJPanel panel = new CreateVehicleJPanel(contentPanel, vehicleDirectory, serviceDirectory, serviceTypes, ownersDirectory);
        contentPanel.add("CreateVehicleJPanel",panel);
        
        CardLayout layout = (CardLayout) contentPanel.getLayout();
        layout.next(contentPanel);
    }//GEN-LAST:event_btnVehicalAndOwnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageVehicles;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnVehicalAndOwner;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel navPanel;
    // End of variables declaration//GEN-END:variables

/// All the demo data for the cars, services and owners
    private void generateDemoData(){
        
        Owner newOwner = ownersDirectory.addOwners();
        newOwner.setOwnerFirstName("John");
        newOwner.setOwnerLastName("Doe");
        newOwner.setOwnerID(1);
        newOwner.setServiceDate(LocalDateTime.of(2026, 1, 1, 0, 0));
        
        Vehicle newVehicle = vehicleDirectory.addVehicle();
        newVehicle.setMake("Kia");
        newVehicle.setModel("Soul SE");
        newVehicle.setYear(2014);
        newVehicle.setVehicleID(1);
        newVehicle.setRegistrationNumber("65465564");
        newVehicle.setOwner(newOwner);
        
        Service newService = serviceDirectory.addService();
        newService.setCost(55.5f);
        newService.setMechanicFirstName("Bob");
        newService.setMechanicLastName("Fixit");
        newService.setServiceDuration(95);
        newService.setServiceID(1);
        newService.setServiceType(serviceTypes.getServiceTypes().get(1));
        newVehicle.setServiceOpted(newService);

        
        Owner newOwner2 = ownersDirectory.addOwners();
        newOwner2.setOwnerFirstName("Bill");
        newOwner2.setOwnerLastName("TheKid");
        newOwner2.setOwnerID(2);
        newOwner2.setServiceDate(LocalDateTime.of(2026, 1, 1, 0, 0));
        
        Vehicle newVehicle2 = vehicleDirectory.addVehicle();
        newVehicle2.setMake("Ford");
        newVehicle2.setModel("Taurus xl");
        newVehicle2.setYear(2010);
        newVehicle2.setVehicleID(2);
        newVehicle2.setRegistrationNumber("26234126123");
        newVehicle2.setOwner(newOwner2);
        
        Service newService2 = serviceDirectory.addService();
        newService2.setCost(55.5f);
        newService2.setMechanicFirstName("Bill");
        newService2.setMechanicLastName("Fixit Jr");
        newService2.setServiceDuration(55);
        newService2.setServiceID(2);
        newService2.setServiceType(serviceTypes.getServiceTypes().get(1));
        newVehicle2.setServiceOpted(newService2);

        Owner newOwner3 = ownersDirectory.addOwners();
        newOwner3.setOwnerFirstName("Joey");
        newOwner3.setOwnerLastName("Smith");
        newOwner3.setOwnerID(3);
        newOwner3.setServiceDate(LocalDateTime.of(2026, 3, 15, 0, 0));

        Vehicle newVehicle3 = vehicleDirectory.addVehicle();
        newVehicle3.setMake("Toyota");
        newVehicle3.setModel("Camry");
        newVehicle3.setYear(2018);
        newVehicle3.setVehicleID(3);
        newVehicle3.setRegistrationNumber("373452aa37234");
        newVehicle3.setOwner(newOwner3);

        Service newService3 = serviceDirectory.addService();
        newService3.setCost(80.0f);
        newService3.setMechanicFirstName("Mike");
        newService3.setMechanicLastName("Wrench");
        newService3.setServiceDuration(40);
        newService3.setServiceID(3);
        newService3.setServiceType(serviceTypes.getServiceTypes().get(2));
        newVehicle3.setServiceOpted(newService3);
        
        Owner newOwner4 = ownersDirectory.addOwners();
        newOwner4.setOwnerFirstName("Alex");
        newOwner4.setOwnerLastName("Washington");
        newOwner4.setOwnerID(4);
        newOwner4.setServiceDate(LocalDateTime.of(2026, 6, 20, 0, 0));

        Vehicle newVehicle4 = vehicleDirectory.addVehicle();
        newVehicle4.setMake("Honda");
        newVehicle4.setModel("Civic");
        newVehicle4.setYear(2001);
        newVehicle4.setVehicleID(4);
        newVehicle4.setRegistrationNumber("3744566435348345");
        newVehicle4.setOwner(newOwner4);

        Service newService4 = serviceDirectory.addService();
        newService4.setCost(120.75f);
        newService4.setMechanicFirstName("Omar");
        newService4.setMechanicLastName("Johnson");
        newService4.setServiceDuration(90);
        newService4.setServiceID(4);
        newService4.setServiceType(serviceTypes.getServiceTypes().get(0));
        newVehicle4.setServiceOpted(newService4);
        
        Owner newOwner5 = ownersDirectory.addOwners();
        newOwner5.setOwnerFirstName("Maria");
        newOwner5.setOwnerLastName("Basil");
        newOwner5.setOwnerID(5);
        newOwner5.setServiceDate(LocalDateTime.of(2026, 9, 5, 0, 0));

        Vehicle newVehicle5 = vehicleDirectory.addVehicle();
        newVehicle5.setMake("Chevrolet");
        newVehicle5.setModel("Malibu");
        newVehicle5.setYear(2009);
        newVehicle5.setVehicleID(5);
        newVehicle5.setRegistrationNumber("594559456");
        newVehicle5.setOwner(newOwner5);

        Service newService5 = serviceDirectory.addService();
        newService5.setCost(64.99f);
        newService5.setMechanicFirstName("Ted");
        newService5.setMechanicLastName("Brooks");
        newService5.setServiceDuration(30);
        newService5.setServiceID(5);
        newService5.setServiceType(serviceTypes.getServiceTypes().get(1));
        newVehicle5.setServiceOpted(newService5);
    }


}
